name: Update Proxy IP Status

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  update-proxies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Update proxy status
      env:
        IP_FILE: 'cek/anu.txt'
        API_URL: 'https://check.installer.us.kg/check?ip={ip}:{port}'
      run: |
        python cek/update_proxy_status.py

    - name: Create error.txt if not exists
      run: |
        touch cek/error.txt

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git add cek/output.txt || true
        git add cek/error.txt || true
        if git diff --cached --exit-code; then
          echo "No changes to commit"
        else
          git commit -m "Update proxy IP status"
          git push
        fi
